#!/usr/bin/env python3
"""Reduce NinjaOne's 768KB OpenAPI spec to just the surface this app consumes.

The whole spec is too large and too noisy to commit or diff — it changes on every
vendor release for reasons that have nothing to do with us. This writes a stable
digest of exactly the endpoints, parameters and enum values the toolkit depends on,
so `docs/api/ninjaone-surface.md` diffs only when *our* contract moves.

Why this exists: every backend test mocks NinjaOne against hand-written fixtures, so
the suite asserts what the maintainer believes the API returns, not what it returns.
The 0.13.3 `is_pending` bug was exactly that — the code assumed an allow-list of
three statuses and NinjaOne's own endpoint titles promise more. A new enum value
still passes every test green and silently misreports a fleet.

Usage:  python3 scripts/ninjaone-spec-digest.py <spec.yaml> > docs/api/ninjaone-surface.md
"""
import re
import sys

# The paths this app actually calls. Templated segments are matched by shape, since
# the spec spells them with its own parameter names.
PATHS = [
    "/activities",
    "/automation/scripts",
    "/device/{id}/patch/os/apply",
    "/device/{id}/patch/os/scan",
    "/device/{id}/patch/software/apply",
    "/device/{id}/patch/software/scan",
    "/device/{id}/reboot/{mode}",
    "/device/{id}/script/run",
    "/device/{id}/scripting/options",
    "/devices-detailed",
    "/locations",
    "/organizations",
    "/queries/os-patch-installs",
    "/queries/os-patches",
    "/queries/software-patch-installs",
    "/queries/software-patches",
    "/roles",
]

# The schemas this app actually deserializes. Attribution is the whole point: a
# first cut collected every `severity` enum in the spec and flagged MAJOR/MINOR as
# values `Severity::from_raw` does not handle — but those belong to
# `PolicyCondition`, which this app never touches. A gate that cries wolf gets
# ignored exactly when it is right, so tickets, invoices and licence schemas are
# out of scope by construction rather than by filtering after the fact.
SCHEMAS = [
    "Activity",
    "DeviceOSPatch",
    "DeviceSoftwarePatch",
    "Location",
    "NodeRole",
    "OSPatchReport",
    "Organization",
    "RunScriptRequest",
    "Script",
    "ScriptVariable",
    "SoftwarePatchReport",
]

# Fields whose vocabulary the toolkit branches on. A value the code does not handle
# is a silent misread; a field with NO enum is a different and equally important
# fact — it means the vendor promises nothing and the parser must stay total.
BRANCHED_FIELDS = [
    "severity", "status", "type", "activityResult", "statusCode", "rebootMode",
]


def normalise(path: str) -> str:
    """Compare paths the way the client builds them.

    The client sets its base URL to `{instance}/api/v2` and appends the paths above,
    so spec path `/v2/organizations` is this app's `/organizations`. Parameter names
    are collapsed too, so the spec's `{id}` compares equal whatever it is called.
    """
    path = re.sub(r"^/v2", "", path)
    return re.sub(r"\{[^}]+\}", "{}", path)


def main() -> int:
    spec = open(sys.argv[1], encoding="utf-8").read()
    lines = spec.splitlines()
    wanted = {normalise(p) for p in PATHS}

    # Index top-level `paths:` entries by line number without a YAML parser — the
    # spec is 20k lines and this only needs structure, not semantics.
    out = ["# NinjaOne API surface used by this toolkit", ""]
    out.append(
        "Generated by `scripts/ninjaone-spec-digest.py` from NinjaOne's published "
        "OpenAPI spec. **Do not edit by hand.** The `ninjaone-contract` CI job "
        "re-fetches the spec weekly and fails when this file would change — that "
        "failure is the signal to check whether a vendor change breaks an assumption "
        "in `model.rs`, `filter.rs` or `rows/`."
    )
    out.append("")

    found = {}
    current = None
    for i, line in enumerate(lines):
        m = re.match(r"^  (/\S+):\s*$", line)
        if m:
            current = m.group(1)
            if normalise(current) in wanted:
                found[current] = i
            continue

    out.append("## Endpoints")
    out.append("")
    for path in sorted(found):
        start = found[path]
        # Walk to the next top-level path entry.
        end = len(lines)
        for j in range(start + 1, len(lines)):
            if re.match(r"^  /\S+:\s*$", lines[j]):
                end = j
                break
        block = lines[start:end]
        methods = sorted({
            mm.group(1).upper()
            for mm in (re.match(r"^    (get|post|put|patch|delete):\s*$", b) for b in block)
            if mm
        })
        params = sorted({
            pm.group(1)
            for pm in (re.search(r"^\s+- name: (\S+)", b) for b in block)
            if pm
        })
        out.append(f"### `{path}`")
        out.append("")
        out.append(f"- methods: {', '.join(methods) or '(none found)'}")
        if params:
            out.append(f"- parameters: {', '.join(params)}")
        out.append("")

    missing = sorted(wanted - {normalise(p) for p in found})
    if missing:
        out.append("### Not found in this spec revision")
        out.append("")
        out.append(
            "These are called by the toolkit but no longer appear in the spec. "
            "That is either a vendor removal or a rename, and either way it breaks a "
            "code path:"
        )
        out.append("")
        for p in missing:
            out.append(f"- `{p}`")
        out.append("")

    # Schema fields, and — the point of the exercise — which of the ones the code
    # branches on carry a closed vocabulary and which are free-form strings.
    blocks = {}
    for i, line in enumerate(lines):
        sm = re.match(r"^    (\w+):\s*$", line)
        if sm and sm.group(1) in SCHEMAS:
            end = len(lines)
            for j in range(i + 1, len(lines)):
                if re.match(r"^    \S", lines[j]):
                    end = j
                    break
            blocks[sm.group(1)] = lines[i:end]

    out.append("## Schemas this app deserializes")
    out.append("")
    out.append(
        "For each field the toolkit branches on: the vocabulary the spec declares, or "
        "**free-form** when it declares none. A free-form field is the vendor "
        "promising nothing — the parser must stay total and must not treat its own "
        "list as exhaustive."
    )
    out.append("")

    for name in sorted(blocks):
        block = blocks[name]
        out.append(f"### `{name}`")
        out.append("")
        for i, line in enumerate(block):
            fm = re.match(r"^        (\w+):\s*$", line)
            if not fm or fm.group(1) not in BRANCHED_FIELDS:
                continue
            field = fm.group(1)
            values = []
            for j in range(i + 1, len(block)):
                if re.match(r"^        \S", block[j]):
                    break
                if re.match(r"^\s+enum:\s*$", block[j]):
                    for k in range(j + 1, len(block)):
                        vm = re.match(r"^\s+- (\S+)\s*$", block[k])
                        if not vm:
                            break
                        values.append(vm.group(1))
                    break
            if not values:
                out.append(f"- `{field}` — **free-form string**, no enum declared")
            elif field == "statusCode":
                out.append(
                    f"- `{field}` — {len(values)} values (count only: NinjaOne's whole "
                    "activity vocabulary, which grows every release; "
                    "`actions::is_action_activity` matches the handful the native "
                    "action endpoints emit)"
                )
            else:
                out.append(f"- `{field}` — `{'`, `'.join(values)}`")
        out.append("")

    print("\n".join(out).rstrip() + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
