//! Renders a self-contained HTML executive report from a cached query result:
//! inline CSS + inline SVG charts, no external assets and no new dependencies, so
//! the file emails/shares cleanly and prints to PDF from any browser. Every piece
//! of NinjaOne text (org / device / patch names) is HTML-escaped before it is
//! interpolated, so a hostile name can't inject markup into the report.

use std::fmt::Write;

use crate::rows::{
    AgeBucket, ComplianceBucket, DeviceSummary, FailureGroup, OrgSeverity, QueryResult,
    SeverityCounts,
};

/// At most this many table rows are rendered per section; a fleet-scale failure or
/// reboot list is summarized rather than dumped (a note records the truncation).
const MAX_TABLE_ROWS: usize = 100;

/// Severity bands in most-to-least-urgent order, paired with their bar color.
const SEVERITY_BANDS: [(&str, &str); 6] = [
    ("Critical", "#dc2626"),
    ("Important", "#ea580c"),
    ("Moderate", "#d97706"),
    ("Low", "#2563eb"),
    ("Optional", "#6b7280"),
    ("Unknown", "#9ca3af"),
];

/// Escapes the five HTML-significant characters so interpolated names can't inject
/// markup (or break the surrounding attribute/element) into the report.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            other => out.push(other),
        }
    }
    out
}

/// Linear bar length: `value/max` of `track` pixels, guarding a zero/empty max and
/// clamping to the track so an out-of-range value never overshoots.
fn bar_len(value: f64, max: f64, track: f64) -> f64 {
    if max <= 0.0 {
        0.0
    } else {
        (value / max).clamp(0.0, 1.0) * track
    }
}

/// Compliance bar color: green at/above 95%, amber at/above 80%, otherwise red.
fn compliance_color(pct: f64) -> &'static str {
    if pct >= 95.0 {
        "#16a34a"
    } else if pct >= 80.0 {
        "#d97706"
    } else {
        "#dc2626"
    }
}

/// Sums the per-org pending-severity breakdowns into a single fleet total.
fn total_severity(by_org: &[OrgSeverity]) -> SeverityCounts {
    let mut t = SeverityCounts::default();
    for o in by_org {
        t.critical += o.counts.critical;
        t.important += o.counts.important;
        t.moderate += o.counts.moderate;
        t.low += o.counts.low;
        t.optional += o.counts.optional;
        t.unknown += o.counts.unknown;
    }
    t
}

/// Reads a severity band's count off a `SeverityCounts` by its `SEVERITY_BANDS`
/// label (the catch-all is `Unknown`).
fn severity_value(counts: &SeverityCounts, label: &str) -> usize {
    match label {
        "Critical" => counts.critical,
        "Important" => counts.important,
        "Moderate" => counts.moderate,
        "Low" => counts.low,
        "Optional" => counts.optional,
        _ => counts.unknown,
    }
}

/// Builds the standalone HTML report. Infallible — writing into a `String` via
/// `std::fmt::Write` never errors.
pub fn render_report(result: &QueryResult) -> String {
    let mut buf = String::with_capacity(8 * 1024);
    buf.push_str("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
    buf.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    buf.push_str("<title>NinjaOne Patch Compliance Report</title><style>");
    buf.push_str(REPORT_CSS);
    buf.push_str("</style></head><body>");

    let generated = escape_html(&result.generated_at);
    let _ = write!(
        buf,
        "<header><h1>NinjaOne Patch Compliance Report</h1>\
         <p class=\"meta\">Generated {generated} \u{00b7} {devices} devices \u{00b7} {rows} patch rows</p>\
         </header>",
        devices = result.devices_total,
        rows = result.rows.len()
    );

    buf.push_str("<section><h2>Compliance by organization</h2>");
    write_compliance_chart(&mut buf, &result.compliance);
    buf.push_str("</section>");

    buf.push_str("<section><h2>Pending patches by severity</h2>");
    write_severity_chart(&mut buf, &total_severity(&result.severity_by_org));
    buf.push_str("</section>");

    buf.push_str("<section><h2>Pending patch age</h2>");
    write_age_chart(&mut buf, &result.age_buckets);
    buf.push_str("</section>");

    buf.push_str("<section><h2>Top patch failures</h2>");
    write_failures_table(&mut buf, &result.failures);
    buf.push_str("</section>");

    buf.push_str("<section><h2>Devices needing reboot</h2>");
    write_reboot_table(&mut buf, &result.devices);
    buf.push_str("</section>");

    buf.push_str(
        "<footer>Generated by NinjaOne Patch Toolkit \u{2014} read-only reporting. \
         Print to PDF to share.</footer></body></html>",
    );
    buf
}

fn write_compliance_chart(buf: &mut String, compliance: &[ComplianceBucket]) {
    if compliance.is_empty() {
        buf.push_str("<p class=\"empty\">No compliance data for this query.</p>");
        return;
    }
    let track = 320.0_f64;
    let bar_x = 210_i32;
    let row_h = 30_i32;
    let height = compliance.len() as i32 * row_h + 12;
    let width = bar_x + track as i32 + 64;
    let _ = write!(
        buf,
        "<svg class=\"chart\" role=\"img\" viewBox=\"0 0 {width} {height}\" width=\"{width}\" height=\"{height}\">"
    );
    for (i, b) in compliance.iter().enumerate() {
        let cy = i as i32 * row_h + row_h / 2 + 6;
        let rect_y = cy - 8;
        let text_y = cy + 4;
        let bar = bar_len(b.compliance_pct, 100.0, track);
        let color = compliance_color(b.compliance_pct);
        let org = escape_html(&b.organization);
        let val_x = bar_x as f64 + track + 8.0;
        let _ = write!(
            buf,
            "<text x=\"0\" y=\"{text_y}\" class=\"lbl\">{org}</text>\
             <rect class=\"track\" x=\"{bar_x}\" y=\"{rect_y}\" width=\"{track:.0}\" height=\"16\" rx=\"3\"/>\
             <rect x=\"{bar_x}\" y=\"{rect_y}\" width=\"{bar:.1}\" height=\"16\" rx=\"3\" fill=\"{color}\"/>\
             <text x=\"{val_x:.0}\" y=\"{text_y}\" class=\"val\">{pct:.0}%</text>",
            pct = b.compliance_pct
        );
    }
    buf.push_str("</svg>");
}

fn write_severity_chart(buf: &mut String, total: &SeverityCounts) {
    let sum = total.critical
        + total.important
        + total.moderate
        + total.low
        + total.optional
        + total.unknown;
    if sum == 0 {
        buf.push_str("<p class=\"empty\">No pending patches.</p>");
        return;
    }
    let track = 620.0_f64;
    let _ = write!(
        buf,
        "<svg class=\"chart\" role=\"img\" viewBox=\"0 0 {w} 34\" width=\"{w}\" height=\"34\">",
        w = track as i32
    );
    let mut x = 0.0_f64;
    for (label, color) in SEVERITY_BANDS {
        let v = severity_value(total, label);
        if v == 0 {
            continue;
        }
        let seg = v as f64 / sum as f64 * track;
        let _ = write!(
            buf,
            "<rect x=\"{x:.1}\" y=\"5\" width=\"{seg:.1}\" height=\"24\" fill=\"{color}\"/>"
        );
        x += seg;
    }
    buf.push_str("</svg><ul class=\"legend\">");
    for (label, color) in SEVERITY_BANDS {
        let v = severity_value(total, label);
        if v == 0 {
            continue;
        }
        let _ = write!(
            buf,
            "<li><span class=\"swatch\" style=\"background:{color}\"></span>{label}: {v}</li>"
        );
    }
    buf.push_str("</ul>");
}

fn write_age_chart(buf: &mut String, buckets: &[AgeBucket]) {
    let max = buckets.iter().map(|b| b.count).max().unwrap_or(0);
    if max == 0 {
        buf.push_str("<p class=\"empty\">No pending patches.</p>");
        return;
    }
    let bar_w = 80_i32;
    let gap = 24_i32;
    let full_h = 140.0_f64;
    let top_pad = 16_i32;
    let width = gap + buckets.len() as i32 * (bar_w + gap);
    let height = full_h as i32 + top_pad + 24;
    let baseline = top_pad as f64 + full_h;
    let _ = write!(
        buf,
        "<svg class=\"chart\" role=\"img\" viewBox=\"0 0 {width} {height}\" width=\"{width}\" height=\"{height}\">"
    );
    for (i, b) in buckets.iter().enumerate() {
        let h = bar_len(b.count as f64, max as f64, full_h);
        let x = gap + i as i32 * (bar_w + gap);
        let y = baseline - h;
        let cx = x + bar_w / 2;
        let label = escape_html(&b.label);
        let _ = write!(
            buf,
            "<rect x=\"{x}\" y=\"{y:.1}\" width=\"{bar_w}\" height=\"{h:.1}\" rx=\"3\" fill=\"#2563eb\"/>\
             <text x=\"{cx}\" y=\"{ty:.1}\" class=\"bar-val\" text-anchor=\"middle\">{count}</text>\
             <text x=\"{cx}\" y=\"{ly}\" class=\"bar-lbl\" text-anchor=\"middle\">{label}</text>",
            ty = y - 4.0,
            ly = baseline as i32 + 16,
            count = b.count
        );
    }
    buf.push_str("</svg>");
}

fn write_failures_table(buf: &mut String, failures: &[FailureGroup]) {
    if failures.is_empty() {
        buf.push_str(
            "<p class=\"empty\">No patch failures in this query. \
             Select the FAILED status and run a query to analyze failures.</p>",
        );
        return;
    }
    buf.push_str(
        "<table><thead><tr><th>Severity</th><th>KB</th><th>Patch</th>\
         <th>Affected devices</th><th>Sample devices</th><th>Latest failure</th></tr></thead><tbody>",
    );
    for f in failures.iter().take(MAX_TABLE_ROWS) {
        let sev = escape_html(&f.severity);
        let kb = escape_html(f.kb.as_deref().unwrap_or("\u{2014}"));
        let name = escape_html(&f.name);
        let sample = escape_html(&f.sample_devices.join(", "));
        let latest = escape_html(f.latest_failure.as_deref().unwrap_or("\u{2014}"));
        let _ = write!(
            buf,
            "<tr><td>{sev}</td><td>{kb}</td><td>{name}</td>\
             <td class=\"num\">{n}</td><td>{sample}</td><td>{latest}</td></tr>",
            n = f.affected_devices
        );
    }
    buf.push_str("</tbody></table>");
    if failures.len() > MAX_TABLE_ROWS {
        let _ = write!(
            buf,
            "<p class=\"empty\">Showing the top {MAX_TABLE_ROWS} of {} failing patches.</p>",
            failures.len()
        );
    }
}

fn write_reboot_table(buf: &mut String, devices: &[DeviceSummary]) {
    let reboot: Vec<&DeviceSummary> = devices.iter().filter(|d| d.needs_reboot).collect();
    if reboot.is_empty() {
        buf.push_str("<p class=\"empty\">No devices are waiting on a reboot.</p>");
        return;
    }
    buf.push_str(
        "<table><thead><tr><th>Organization</th><th>Location</th><th>Role</th>\
         <th>Device</th><th>OS</th><th>Pending patches</th></tr></thead><tbody>",
    );
    for d in reboot.iter().take(MAX_TABLE_ROWS) {
        let org = escape_html(&d.organization);
        let loc = escape_html(d.location.as_deref().unwrap_or("\u{2014}"));
        let role = escape_html(d.device_role.as_deref().unwrap_or("\u{2014}"));
        let dev = escape_html(&d.device_name);
        let os = escape_html(d.os_name.as_deref().unwrap_or("\u{2014}"));
        let _ = write!(
            buf,
            "<tr><td>{org}</td><td>{loc}</td><td>{role}</td><td>{dev}</td>\
             <td>{os}</td><td class=\"num\">{n}</td></tr>",
            n = d.pending_count
        );
    }
    buf.push_str("</tbody></table>");
    if reboot.len() > MAX_TABLE_ROWS {
        let _ = write!(
            buf,
            "<p class=\"empty\">Showing {MAX_TABLE_ROWS} of {} devices needing reboot.</p>",
            reboot.len()
        );
    }
}

/// Print-friendly light theme — no external fonts/assets so the report renders
/// identically offline and prints cleanly.
const REPORT_CSS: &str = "\
*{box-sizing:border-box}\
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1f2937;\
max-width:900px;margin:0 auto;padding:32px;line-height:1.4}\
header{border-bottom:2px solid #1f2a37;padding-bottom:12px;margin-bottom:8px}\
h1{font-size:22px;margin:0 0 4px}\
.meta{color:#6b7280;font-size:13px;margin:0}\
section{margin:24px 0;page-break-inside:avoid}\
h2{font-size:16px;border-left:4px solid #1f2a37;padding-left:8px;margin:0 0 12px}\
table{border-collapse:collapse;width:100%;font-size:13px}\
th,td{text-align:left;padding:6px 8px;border-bottom:1px solid #e5e7eb;vertical-align:top}\
th{background:#f3f4f6}\
td.num{text-align:right;font-variant-numeric:tabular-nums}\
.empty{color:#6b7280;font-style:italic}\
.chart{max-width:100%;height:auto}\
.chart .track{fill:#e5e7eb}\
.chart .lbl,.chart .val,.chart .bar-val,.chart .bar-lbl{font:12px sans-serif;fill:#374151}\
.legend{list-style:none;display:flex;flex-wrap:wrap;gap:12px;padding:8px 0 0;margin:0;font-size:12px}\
.legend li{display:flex;align-items:center;gap:6px}\
.swatch{width:12px;height:12px;border-radius:2px;display:inline-block}\
footer{margin-top:32px;color:#9ca3af;font-size:11px;border-top:1px solid #e5e7eb;padding-top:8px}\
@media print{body{padding:0}}";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escape_html_escapes_markup() {
        assert_eq!(
            escape_html("<b>&\"'"),
            "&lt;b&gt;&amp;&quot;&#39;",
            "all five HTML-significant characters are escaped"
        );
        assert_eq!(escape_html("plain text"), "plain text");
    }

    #[test]
    fn bar_len_guards_zero_max_and_clamps() {
        assert_eq!(bar_len(50.0, 0.0, 100.0), 0.0, "zero max → no bar");
        assert_eq!(bar_len(50.0, 100.0, 200.0), 100.0);
        assert_eq!(bar_len(150.0, 100.0, 200.0), 200.0, "over-range clamps");
    }

    #[test]
    fn total_severity_sums_each_band_across_orgs() {
        let by_org = vec![
            OrgSeverity {
                organization: "A".into(),
                counts: SeverityCounts {
                    critical: 2,
                    important: 1,
                    ..Default::default()
                },
            },
            OrgSeverity {
                organization: "B".into(),
                counts: SeverityCounts {
                    critical: 3,
                    low: 4,
                    ..Default::default()
                },
            },
        ];
        let t = total_severity(&by_org);
        assert_eq!(t.critical, 5);
        assert_eq!(t.important, 1);
        assert_eq!(t.low, 4);
    }

    fn sample_result() -> QueryResult {
        QueryResult {
            rows: Vec::new(),
            devices: vec![DeviceSummary {
                device_id: 1,
                device_name: "web-01".into(),
                organization: "Contoso".into(),
                location: Some("HQ".into()),
                device_role: None,
                os_name: Some("Windows Server 2022".into()),
                node_class: None,
                needs_reboot: true,
                pending_count: 3,
            }],
            compliance: vec![ComplianceBucket {
                // A hostile org name must be escaped, not rendered as markup.
                organization: "<script>alert(1)</script>".into(),
                devices_total: 10,
                devices_compliant: 9,
                compliance_pct: 90.0,
                pending_critical: 1,
                aged_critical: 0,
            }],
            failures: vec![FailureGroup {
                patch_type: "OS".into(),
                kb: Some("KB1".into()),
                name: "<img src=x onerror=alert(1)>".into(),
                severity: "Critical".into(),
                severity_rank: 5,
                affected_devices: 4,
                sample_devices: vec!["web-01".into()],
                latest_failure: Some("2026-05-01 00:00 UTC".into()),
                latest_failure_ts: Some(1_777_000_000),
            }],
            severity_by_org: vec![OrgSeverity {
                organization: "Contoso".into(),
                counts: SeverityCounts {
                    critical: 1,
                    important: 2,
                    ..Default::default()
                },
            }],
            age_buckets: vec![
                AgeBucket {
                    label: "0-30 days".into(),
                    count: 2,
                },
                AgeBucket {
                    label: "180+ days".into(),
                    count: 1,
                },
            ],
            devices_total: 10,
            generated_at: "2026-01-01 00:00:00 UTC".into(),
        }
    }

    #[test]
    fn render_report_escapes_names_and_includes_every_section() {
        let html = render_report(&sample_result());
        // Hostile names are escaped, never emitted as live markup.
        assert!(html.contains("&lt;script&gt;"), "org name escaped");
        assert!(
            !html.contains("<script>alert"),
            "no unescaped script survives"
        );
        assert!(
            !html.contains("<img src=x"),
            "no unescaped patch-name markup survives"
        );
        // All five sections are present.
        for heading in [
            "Compliance by organization",
            "Pending patches by severity",
            "Pending patch age",
            "Top patch failures",
            "Devices needing reboot",
        ] {
            assert!(html.contains(heading), "missing section: {heading}");
        }
        // Well-formed standalone document.
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.trim_end().ends_with("</html>"));
    }

    #[test]
    fn render_report_handles_empty_result_without_panicking() {
        let empty = QueryResult {
            rows: Vec::new(),
            devices: Vec::new(),
            compliance: Vec::new(),
            failures: Vec::new(),
            severity_by_org: Vec::new(),
            age_buckets: Vec::new(),
            devices_total: 0,
            generated_at: "2026-01-01 00:00:00 UTC".into(),
        };
        let html = render_report(&empty);
        assert!(html.contains("No compliance data"));
        assert!(html.contains("No patch failures"));
    }
}
